#!/bin/sh -e

meson setup builddir \
    --prefix=/usr \
    -Dbash_completion=disabled \
    -Dzsh_completion=disabled \
    -Dman=disabled \
    -Dtests=false \
    -Dselinux=disabled \

ninja -C builddir
ninja -C builddir install
